services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  nourshawky03/dsci522-project:d86adb0
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64